### ISSUE TITLE
PicoMemcard+ infinite next file

### ISSUE THREAD

**Issue by Raphfriend** [dangiu/PicoMemcard#16]
If you move on to the next file (START + SELECT + DPAD UP) and keep going indefinitely, even if you only have one additional file, the system will interpret it as a new file and it will be necessary to go back (START + SELECT + DPAD DOWN) every single time the next file command was pressed.

**Comment by Androxilogin** [comment]
I found this annoying too. I was thinking just a blinking light to notify the user when they reached the end of their list without reloading the current card data would be cool. Also, perhaps a key combo to create a new empty card? I know the original PicoMem (not+) has Start + Select + Triangle to force the card to read, perhaps implement that combo for new card here?
