### ISSUE TITLE
blinking green light on psx

### ISSUE THREAD

**Issue by MrFilz** [dangiu/PicoMemcard#28]
I build my own picomemcard+ thanks to your project, but i can not get it to work on my playstation. I can write the pico+ firmware to the raspberry, and after a half minute or so the sd card folder opens. It is a 4GB micro sd fat32 formated with 0.MCR and 1.MCR on it. If i plug it into the playstation there is only a blinking green light and no card is recognized... Am i doing something wrong?

**Comment by dangiu** [comment]
That's an issue I haven't seen before. So the SD card pops up when the Pico is attached via USB to the computer but does not work on the PSX and keeps blinking? The only thing that comes to my mind is that the microSD is not powered correctly when attached to the PSX, could you share a photo of the build? (in particular the various connections?)

**Comment by MrFilz** [comment]
I used a cheap china clone mc for my build. I disconnected all pins from the rest of the board, and attached a pico on top. insulated the bottom of the pico with kapton tape and soldered the pico with its ground points to the board. So in the end every trace beneath the pins of the mc are now ground. This gave me a nice and solid connection. This was for the picomemcard. And it worked flawless after i wrote the firmware and disconnected it save from my laptop! A few weeks later i decided to try picomemcard+ and ordered basically the sd module from your github pictures. I desoldered the  headers and put it on top of the mc housing. Connected all with wires like this:
PIco 33 - ground SD module
Pico 40 - VCC SD module
Pico 21 - MOSO SD module
Pico 25 - MOSI SD module
Pico 24 - SCK SD module
Pico 22 - CS SD module

So the sd card is powered correct if connected to usb. 5V goes in, and the power regulator on the SD module provides 3,28V, according to my multimeter, for the sd card. But the Playstation is only providing 3,3V, so there are only 2,15V on the sd card after the regulator... but you used the same board on the pictures, so i wonder if i am missing something! I also triple checked everything, no shorts to ground on any pin besides ground, no shorts between the pins...

**Comment by MrFilz** [comment]
![166308715099747784896](https://user-images.githubusercontent.com/49584625/189958432-2234d370-fce0-4fbd-ba78-3205e6ee405b.jpg)
![Uploading 1663087192975540925052.jpg…]()

**Comment by MrFilz** [comment]
![Uploading 1663087279492413240721.jpg…]()

**Comment by MrFilz** [comment]
![Uploading 20220913_184306.jpg…]()

**Comment by MrFilz** [comment]
![20220913_184306](https://user-images.githubusercontent.com/49584625/189959595-663e05c0-70e8-4d0b-b2d7-98cf823b8470.jpg)

**Comment by MrFilz** [comment]
I know it looks wild, but everything is connected like i mentioned it, and there is no short!

**Comment by dangiu** [comment]
You didn't miss anything, looks like your build was well executed too! Which playstation model are you working with?
There is something that you could test.... If you have another Pico on hand you could: disconnect the power provided by the playstation, then connect the second Pico to USB and bridge the VBUS pins (with a jumper wire) in order to power the other Pico (PicoMemcard+) using USB power while connected to the PSX and see if everything works.

**Comment by MrFilz** [comment]
Thanks for your kindness. I have a pal 5502 model with xstation ode installed. Interestingly enough the raspberry pi works flawless as a picomemcard. The issue begins if i try to turn it into a picomemecard+. So i thought the problem must be the sd module itself. And thanks to your guess with the power issue, i tried something else, because i do not have a second pico at hand. Pin 36 on the pico is 3,3V no matter what. It is 3,3V with USB and with the playstation. So i connected pin 36 of the pico with the power rail of the sd module, the right side of c3 on the sd module to be precise! And it worked! The picomemcard+ gives me a solid green, and everything works now! Maybe this helps somemone later! Thank you for this awesome project, and for your help!

**Comment by MrFilz** [comment]
![16631744328011576530355](https://user-images.githubusercontent.com/49584625/190215887-aafe2fb5-6d96-44c8-b013-4315b5b8c083.jpg)
This is what it looks like 😁

**Comment by dangiu** [comment]
Awesome! I'm glad everything works! :)
