### ISSUE TITLE
RP2040-Zero does it have built-in memory?

### ISSUE THREAD

**Issue by amxcs** [dangiu/PicoMemcard#31]
RP2040-Zero does it have built-in memory?
Can it be used without a SD card?
Because after I write PicoMemcard+RP2040-Zero.uf2 it doesn't open as mass storage.

**Comment by amxcs** [comment]
In Version v1.0.0 i found PicoMemcard_RP2040-Zero.uf2 аnd it works.

**Comment by dangiu** [comment]
Yup! That is correct, on the other hand "PicoMemcard+RP2040-Zero.uf2" is the "Plus" version that requires the SD card... Maybe I should change the naming to make it more explicit :)
