### ISSUE TITLE
Play CD backup from picomemcard.

### ISSUE THREAD

**Issue by tomudo** [dangiu/PicoMemcard#33]
Sorry for asking a stupid idea. Is PS1 has capability to play CD backup from picomemcard in the future?

**Comment by dangiu** [comment]
Not a stupid question, but I don't know a precise answer... Let me elaborate. It may technically be possible to do, but it would require writing some sort of low level code that the PSX would execute to mask all the calls to the CD reader and redirect them to memory card. Although this in itself is very difficult (and at the moment I don't have the knowledge to do it myself), what concerns me the most is the fact that the reading speed of memory cards are abysmal. Meaning that even if it's possible, games would end up being terribly slow in the loading process.
