### ISSUE TITLE
Reset from PAD 

### ISSUE THREAD

**Issue by LobAnovich** [dangiu/PicoMemcard#34]
Is it possible to implement a "reset from pad" function?

**Comment by dangiu** [comment]
Might be, but what would be the use of that? It depends on what you want it for, sometimes other software might disable the ability to interact with the memory card via controller.

**Comment by LobAnovich** [comment]
For example, restarting PS One from a wireless pad to select a different game from PSIO without having to go to the console itself

**Comment by dangiu** [comment]
Oh, you mean reasetting the console itself? No, I belive there is no way to do that from the memory card bus unfortunatley :(
