### ISSUE TITLE
Pico is not detected

### ISSUE THREAD

**Issue by Nacheras** [dangiu/PicoMemcard#43]
When it try to flash "PicoMemcard+.uf2" , windows detects the pico when pressing the BOOTSEL button, I copy the .uf2 archive and then it is supossed to show the Pico as a usb device to copy the mecard.mcr, but it doesn´t. It just show me the device as a letter. I have tried with different computers.
![imagen](https://user-images.githubusercontent.com/50806386/222759535-5d2aec99-0417-4c86-98fc-37a3c6e65eca.png)
What could be the problem?

**Comment by dangiu** [comment]
Have you soldered the SD card module and inserted the SD card? PicoMemcard+ works only with the MicroSD SPI module, otherwise you need to use the non-plus version (just PicoMemcard).

**Comment by Nacheras** [comment]
Well, that's the problem 😅😅
I will solder the SD module and check it works, thank you!
