### ISSUE TITLE
Hey did you know your project got put into a retail product?

### ISSUE THREAD

**Issue by Kippykip** [dangiu/PicoMemcard#59]
Hey fam, I found these on aliexpress and was curious how it worked
https://www.aliexpress.com/item/1005005071752501.html

Turns out they've just taken your project and made a full product out of it.
![image_2023-05-17_000214933](https://github.com/dangiu/PicoMemcard/assets/33023808/a863ef63-0b5a-4944-9788-16e38a5aade7)
![image_2023-05-17_000340239](https://github.com/dangiu/PicoMemcard/assets/33023808/b21542da-9b30-4635-9a26-5f7c2d778113)

**Comment by realJoshByrnes** [comment]
There's been a bit of a discussion about this on #46 - It's built well, and whilst not part of this project, it uses an old version of this software - that is updatable.
