### ISSUE TITLE
Red LED "Synced" status on Pico W rather than green. 

### ISSUE THREAD

**Issue by Androxilogin** [dangiu/PicoMemcard#64]
The latest update seems to be reversed with the LED status lights. Thanks for the latest update, as usual!

**Comment by dangiu** [comment]
I set it as a pre-release because many people have complaint about different issues, I'll have to work on it a bit more..
Thanks for reporting :)

**Comment by Androxilogin** [comment]
> 

I'm sorry, reading over other 'issues' I see this was already discussed. Thanks!
