### ISSUE TITLE
3D Model of RP2040 zero picomemcard+ is wrong

### ISSUE THREAD

**Issue by SnoopKatt** [dangiu/PicoMemcard#65]
It appears the 3D model for the RP2040 zero version of PicoMemCard+ doesn't match the location of components on the PCB. MrMario2011's video highlights these issues
https://youtu.be/sScJ2m--iaY

**Comment by dangiu** [comment]
Thanks for pointing it out, I will update the model to match the new PCB version!

**Comment by dangiu** [comment]
Fixed

**Comment by SnoopKatt** [comment]
Thanks! That was quick!

**Comment by dangiu** [comment]
The model was already made, I just forgot to upload it :)
