### ISSUE TITLE
Controller doesn't work when plugged in

### ISSUE THREAD

**Issue by Seva167** [dangiu/PicoMemcard#83]
I have a SCPH-7000 Japanese console and aliexpress Psxmemcard, when i try to plug it in bios acts like controller is unplugged, when already in memory card menu, it still doesn't work.

Is this aliexpress memcard issue or japanese bios issue?
Tried different memcard and controller slots.

Blank firmware still triggers this issue.

**Comment by realJoshByrnes** [comment]
I can't imagine that it would be an incompatible BIOS, but it's always a possibility (the same is true for the controller)

What do you mean by blank firmware? Did you flash the device?

Have you tried with/without the SD card? Does this make a difference?

I suspect that the device may be defective, but it could also be a software issue. As we don't know what's on the device, can you try flashing a different version of PicoMemCard on it?

**Comment by Seva167** [comment]
Tried most of the versions.
Blank firmware is firmware that disables all gpio and goes into infinite loop.

SD card makes no difference except blinking LED indicating error.
RP2040 appears to be working, and i'm not sure how it is even interferes with the controller.
Even when power pins are blocked it still interferes, maybe some pins are shorted somewhere.

**Comment by realJoshByrnes** [comment]
> maybe some pins are shorted somewhere.

Once I read that you're actually installing blank firmware (ensuring you didn't mean a clean PMC install) my first thought was that you have a short.

If you've got a multimeter you could test for continuity between pins.

I'd get in touch with the seller. Hopefully it's just one bad device, and not a bad batch.

**Comment by dangiu** [comment]
> > maybe some pins are shorted somewhere.
> 
> Once I read that you're actually installing blank firmware (ensuring you didn't mean a clean PMC install) my first thought was that you have a short.
> 
> If you've got a multimeter you could test for continuity between pins.
> 
> I'd get in touch with the seller. Hopefully it's just one bad device, and not a bad batch.

Yes I agree that it could be something like this. It interfeers with the controller because memory cards and controllers actually share the same bus on PS1, it could be that a pin is always pulled low by the RP2040 and this prevents any useful communication on the bus.

**Comment by Seva167** [comment]
Looks like in my case pin 2 is shorted with pin 6

**Comment by Seva167** [comment]
Got a refund from aliexpress, ordered a replacement, works now.
